FORMAT: 1A

# Toss

Toss is an application that enables people to connect for quick events.

## Group Users

## Users Collection [/users]

### Create a user [POST]

## Authenticated User [/users/me]

### Get the authenticated user [GET]

+ Response 200 (application/json)
    
        {   
        "first_name": "Camden",
        "last_name": "Bickel",
        "username": "cam"
        }

## User Friends [/users/{user_id}/friends]

+ Parameters
    + user_id (number) - ID of the user
    
### Get all friends [GET]