# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20161023_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='members',
        ),
    ]
