# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0004_remove_conversation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
